--LOC_STATE

--1.SELECTALL
--EXEC PR_LOC_STATE_SELECTALL
CREATE PROC PR_LOC_STATE_SELECTALL
AS
	SELECT 
		LOC_State.StateID,
		StateName,
		LOC_State.StateCode,
		LOC_Country.CountryID,
		LOC_Country.CountryName,
		LOC_Country.CountryCode
	FROM LOC_State
	INNER JOIN LOC_Country
	ON LOC_State.CountryID = LOC_Country.CountryID
	ORDER BY LOC_Country.CountryName, LOC_State.StateName

--2.SELECTBYPK
--EXEC PR_LOC_STATE_SELECTBYPK
CREATE PROC PR_LOC_STATE_SELECTBYPK
@STATEID INT
AS
SELECT
	LOC_State.StateID,
	LOC_State.StateName,
	LOC_State.StateCode,
	LOC_Country.CountryID,
	LOC_Country.CountryName,
	LOC_Country.CountryCode
FROM LOC_State
INNER JOIN LOC_Country
ON LOC_Country.CountryID = LOC_State.CountryID
WHERE LOC_State.StateID = @STATEID
ORDER BY LOC_Country.CountryName,LOC_State.StateName

--3.INSERT
EXEC PR_LOC_STATE_INSERT	
CREATE PROC PR_LOC_STATE_INSERT
@STATENAME VARCHAR(100),
@STATECODE VARCHAR(50),
@COUNTRYID INT
AS
INSERT INTO LOC_State 
	(StateName,StateCode,CountryID)
VALUES (@STATENAME,@STATECODE,@COUNTRYID)

4.UPDATE
ALTER PROC PR_LOC_STATE_UPDATE
@STATEID   INT,
@STATENAME VARCHAR(100),
@STATECODE VARCHAR(50),
@COUNTRYID INT
AS
	UPDATE LOC_State 
		SET StateName = @STATENAME,
			StateCode = @STATECODE,
			CountryID = @COUNTRYID,
			Modified  = GETDATE()
	WHERE LOC_State.StateID  = @STATEID

5.DELETE
CREATE PROC PR_LOC_STATE_DELETE
@STATEID INT
AS
	DELETE FROM LOC_State
	WHERE LOC_State.StateID = @STATEID
